version: '3.8'

services:
  db:
    image: postgres:15
    container_name: genfit_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-group2db}
      - POSTGRES_USER=${POSTGRES_USER:-group2}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-group2}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-group2} -d ${POSTGRES_DB:-group2db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./genfit_django
      dockerfile: Dockerfile
    container_name: genfit_web
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./genfit_django:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-group2db}
      - POSTGRES_USER=${POSTGRES_USER:-group2}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-group2}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - SECRET_KEY=${SECRET_KEY:-django-insecure-p6p*^^1$rp!n(^wo$dqu72al_wq^+5v#kw=8lw#)1i9h5qgq42}
      - DEBUG=${DEBUG:-True}
      - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
