# Generated by Django 5.2 on 2025-12-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessgoal',
            name='goal_type',
            field=models.CharField(choices=[('WALKING_RUNNING', 'Walking/Running'), ('WORKOUT', 'Workout'), ('CYCLING', 'Cycling'), ('SWIMMING', 'Swimming'), ('SPORTS', 'Sports'), ('YOGA', 'Yoga'), ('WEIGHTLIFTING', 'Weightlifting'), ('HIKING', 'Hiking'), ('STEP_COUNT', 'Daily Steps'), ('MEDITATION', 'Meditation'), ('BASKETBALL', 'Basketball'), ('FOOTBALL', 'Football/Soccer'), ('TENNIS', 'Tennis')], max_length=20),
        ),
    ]
