# Generated by Django 5.2 on 2025-12-10 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('CHAT', 'Chat Message'), ('FORUM', 'Forum Post'), ('THREAD', 'Forum Thread'), ('COMMENT', 'Comment'), ('PROFILE', 'User Profile'), ('CHALLENGE', 'Challenge'), ('OTHER', 'Other')], help_text='Type of content being reported', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment or Bullying'), ('inappropriate', 'Inappropriate Content'), ('hate_speech', 'Hate Speech'), ('privacy', 'Privacy Violation'), ('impersonation', 'Impersonation'), ('other', 'Other')], help_text='Reason for reporting', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional details about the report')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from admin reviewing the report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='api_report_status_2ddde8_idx'), models.Index(fields=['content_type', 'object_id'], name='api_report_content_69b99c_idx'), models.Index(fields=['reporter'], name='api_report_reporte_2c0738_idx')],
            },
        ),
    ]
