# Generated by Django 5.2 on 2025-11-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_sports',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
