# Generated by Django 5.2 on 2025-12-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='content_type',
            field=models.CharField(choices=[('CHAT', 'Chat Message'), ('FORUM', 'Forum Post'), ('THREAD', 'Forum Thread'), ('COMMENT', 'Comment'), ('SUBCOMMENT', 'Subcomment'), ('PROFILE', 'User Profile'), ('CHALLENGE', 'Challenge'), ('OTHER', 'Other')], help_text='Type of content being reported', max_length=20),
        ),
    ]
