# Generated by Django 5.2 on 2025-05-11 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_challenge_challengeparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='max_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='min_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
