# Generated by Django 5.2 on 2025-04-24 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('COMMENT', 'Comment'), ('TAG', 'Tag'), ('REPLY', 'Reply'), ('CHALLENGE', 'Challenge Invitation'), ('PROGRESS', 'Challenge Progress'), ('ACHIEVEMENT', 'Achievement'), ('BADGE', 'Badge'), ('GOAL', 'New Goal from Mentor'), ('FEEDBACK', 'Mentor Feedback'), ('SYSTEM', 'System Notification'), ('NEW_MESSAGE', 'New Message'), ('GOAL_INACTIVE', 'Goal Inactive Warning')], max_length=20),
        ),
        migrations.CreateModel(
            name='FitnessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('WALKING_RUNNING', 'Walking/Running'), ('WORKOUT', 'Workout'), ('CYCLING', 'Cycling'), ('SWIMMING', 'Swimming'), ('SPORTS', 'Sports')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_value', models.FloatField(help_text='Target value (e.g., distance in km, duration in minutes)')),
                ('current_value', models.FloatField(default=0.0)),
                ('unit', models.CharField(help_text='Unit of measurement (e.g., km, minutes)', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('target_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('INACTIVE', 'Inactive'), ('RESTARTED', 'Restarted')], default='ACTIVE', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_goals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
