# Generated by Django 5.2 on 2025-12-16 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_threadbookmark'),
        ('api', '0003_report'),
    ]

    operations = [
    ]
