# Generated by Django 5.2 on 2025-11-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_preferred_sports'),
        ('api', '0004_user_preferences'),
    ]

    operations = [
    ]
