# Generated by Django 5.2 on 2025-11-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20251110_1500'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailyadvice',
            new_name='api_dailyad_user_id_40b1fe_idx',
            old_name='api_dailyad_user_id_b8c5e3_idx',
        ),
        migrations.AddField(
            model_name='challenge',
            name='difficulty_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_sports',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
