"""
Django settings for genfit_django project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-p6p*^^1$rp!n(^wo$dqu72al_wq^+5v#kw=8lw#)1i9h5qgq42')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = ['localhost',
                 '127.0.0.1',
                 '10.0.2.2',
                 '165.232.79.200',
                 '164.90.166.81',
                 'genfit.website',
                 'www.genfit.website',
                 'api.genfit.website',
                ]

# For development, allow all origins. In production, use specific origins.
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Allow all origins in development
# CORS_ALLOWED_ORIGINS = ['http://localhost:3000']
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:5173',
    'http://localhost:5174',
    'http://localhost:5000',
    'http://10.0.2.2:8000',
    'http://10.0.2.2:5000',
    'http://10.0.2.2:3000',
    'http://165.232.79.200:8000',
    'http://165.232.79.200:3000',
    'http://165.232.79.200:5000',
    'http://164.90.166.81:8000',
    'http://164.90.166.81:3000',
    'http://164.90.166.81:5000',
    'http://178.243.211.99:8000',
    'http://178.243.211.99:3000',
    'http://178.243.211.99:5000',
    'https://genfit.website',
    'https://www.genfit.website',
    'https://api.genfit.website',
    'http://genfit.website',
    'http://www.genfit.website',
    'http://api.genfit.website',
]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_extensions',
    'corsheaders',
    'api',
    'channels',
    'chat',
]

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'genfit_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'genfit_django.wsgi.application'

ASGI_APPLICATION = 'genfit_django.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'group2db'),
        'USER': os.environ.get('POSTGRES_USER', 'group2'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'group2'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Frontend in Docker
    "http://localhost:5000",
    "http://localhost:8000",
    "http://localhost:5173",
    "http://10.0.2.2:8000",
    "http://10.0.2.2:5000",
    "http://10.0.2.2:3000",
    "https://localhost:3000",
    "https://localhost:5000",
    "https://localhost:8000",
    "https://localhost:5173",
    "https://10.0.2.2:8000",
    "https://10.0.2.2:5000",
    "https://10.0.2.2:3000",
    'http://165.232.79.200:8000',
    'http://165.232.79.200:3000',
    'http://165.232.79.200:5000',
    'http://164.90.166.81:8000',
    'http://164.90.166.81:3000',
    'http://164.90.166.81:5000',
    'https://genfit.website',
    'https://www.genfit.website',
    'https://api.genfit.website',
    'http://genfit.website',
    'http://www.genfit.website',
    'http://api.genfit.website',
    'https://129.212.168.212',
    'http://129.212.168.212',
]


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'api.UserWithType'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session Settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_COOKIE_SECURE = not DEBUG  # Only send cookie over HTTPS in production
SESSION_COOKIE_HTTPONLY = False  # Allow JavaScript access to session cookie for mobile app
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection
CSRF_COOKIE_SECURE = not DEBUG  # Only send CSRF cookie over HTTPS in production

# Security settings for HTTPS
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = False  # Load balancer handles SSL, not Django
    CSRF_COOKIE_DOMAIN = '.genfit.website'
    SESSION_COOKIE_DOMAIN = '.genfit.website'

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
