# Generated by Django 5.2 on 2025-04-29 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='groupchat_name',
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='users_online',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='file',
        ),
    ]
